name: electricity_x_2024
description: Electricity app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  geocoding: ^2.0.5
  geolocator: ^9.0.2
  flutter_svg: ^1.1.5
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  http: ^0.13.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  async_builder: ^1.3.1
  connectivity_plus: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  google_maps_flutter: ^2.2.1
  easy_localization: ^3.0.1
  json_serializable: ^6.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/