name: electricity_x_2024
description: Electricity app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  http: ^0.13.5
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.3.2+2
  easy_localization: ^3.0.1
  flutter_speed_dial: ^6.2.0
  carousel_slider: ^4.2.1
  spring: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/